version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo No build commands needed for static HTML.
artifacts:
  files:
    - index.html
    - scripts/**     # Include all files recursively in the scripts folder
    - appspec.yml    # Include the appspec file for CodeDeploy
