version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo No build commands needed for static HTML.
artifacts:
  files:
    - index.html
